require("msherif.plugins-setup")
require("msherif.core.options")
require("msherif.core.neovide")
require("msherif.core.keymaps")
require("msherif.core.colorscheme")
-- require("msherif.plugins.nvim-tree")
require("msherif.plugins.neo-tree")
require("msherif.plugins.harpoon")
require("msherif.plugins.lualine")
require("msherif.plugins.telescope")
require("msherif.plugins.nvim-cmp")
require("msherif.plugins.lsp.lsp-zero")
require("msherif.plugins.lsp.null-ls")
-- require("msherif.plugins.lsp.lspconfig")
require("msherif.plugins.autopairs")
require("msherif.plugins.treesetter")
require("msherif.plugins.git-signs")
